Implement the Angular position capture
rhomspuron/ni_scripts pull request #1
Opened 2020-11-23 12:57 UTC by Juudyyt

Translate from AngularPosition-Buff-Cont.c to python API

2020-11-23 13:01 UTC, Juudyyt commented
add new file translation

2020-11-23 14:48 UTC, rhomspuron requested changes
Thanks for the contribution!

2020-11-23 14:48 UTC, rhomspuron commented on angularcapture.py
> +@click.argument('encodertype')
https://click.palletsprojects.com/en/7.x/options/
Could you change to use click.Choice?

2020-11-23 14:48 UTC, rhomspuron commented on angularcapture.py
> +
Could you use flake8 to check PEP8?
https://flake8.pycqa.org/en/latest/

2020-11-23 14:48 UTC, rhomspuron commented on angularcapture.py
> +    return argum
You can remove it after to use click.Choice

2020-11-26 10:39 UTC, Juudyyt commented
code correction

2020-11-26 10:40 UTC, Juudyyt commented
code correction

2020-12-01 09:51 UTC, rhomspuron approved these changes

2020-12-01 09:52 UTC, merged

2020-12-01 09:52 UTC, rhomspuron commented
Thanks for the contribution @Juudyyt